### ISSUE TITLE
As a developer, I would like to have an initialized Go backend

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#1]
Initialize Go backend with simple hello world example

**Comment by andrewkucz** [comment]
Resources:

https://github.com/cbrake/goreact
https://medium.com/@madhanganesh/golang-react-application-2aaf3bca92b1

**Comment by carolnavya** [comment]
Successfully able set up a simple webserver to display hello world
reference: https://blog.logrocket.com/creating-a-web-server-with-golang/
