### ISSUE TITLE
As a developer, I want User and Review tables set up and basic endpoints set up

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#22]
Endpoints + table for Users and Reviews
	- Minimum: create both tables with proper columns
	- Review table is going to have a foreign key pointing to an establishment
	- Create basic handlers for both just to test

User will need these fields at minimum, add any more you see fit: email, password, verified (boolean)

See ER diagram (not final)

![image](https://user-images.githubusercontent.com/13070523/152891034-0d7aa0b4-fbc6-487d-8a28-4493ca8bcf31.png)

**Comment by carolnavya** [comment]
Database endpoints successfully set-up in accordance to the ER Diagram
