### ISSUE TITLE
As a user, I want to be able to create an account and verify my email address

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#23]
User account creation with email verification
	- create sign up endpoint 
		- accept their email and a password
		- hash/encrypt password and store user with verified = false
		- send them an email with a verification link that sets verified to true when clicked

Look up tutorials, this is common functionality I'm sure there are some out there

**Comment by carolnavya** [comment]
Completed account creation process.
- A database was created to store user credentials.
- Passwords are encrypted and stored
- Methods to verify User Login credentials included
Pending:
Sending email verification link

**Comment by manjari94** [comment]
The account creation process has been done.

Since only the verification link is pending, this will be continued in Sprint 3 along with other dependent functionality.
