### ISSUE TITLE
As a user, I want a landing page with a search bar 

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#26]
Start basic landing page modelled after Yelp home page

Fill with dummy text / data if necessary, does not need to be connected to api

Only need top 2 sections, see screenshot:

![Screenshot 2022-02-07 183326](https://user-images.githubusercontent.com/13070523/152891638-737f22c6-f5d1-46ee-95ec-173f26e14876.png)

Use a nice picture of Gainesville or campus as the header

**Comment by andrewkucz** [comment]
I just pushed a change to set up the page for you to create.

You should probably be building the page in the file: `frontend\src\pages\LandingPage\index.tsx`

and putting any components related to that page in that folder. Lmk if you have any questions

**Comment by Monicakodali** [comment]
Completed
