### ISSUE TITLE
As a user, I want to be able to log in and create an account

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#29]
Create the basic log in and sign up pages.

Simple design with text fields for login credentials in center.

**Comment by andrewkucz** [comment]
Same with this story, I created the file for the page. You will be building the login / signup page in `frontend\src\pages\LoginPage\index.tsx`

**Comment by Monicakodali** [comment]
[https://surajsharma.net/blog/react-login-form-typescript](url)
