### ISSUE TITLE
As a user, I want to be able to create an account

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#53]
For the backend, we need to create a route that allows a user to signup. The user should be created in the database with `verified=false`  The route should send an email to the user for confirmation that when clicked, updates their verified status to true.

There is probably tutorials online for doing this

**Comment by manjari94** [comment]
Basic authentication is done for signup and login. 
Further updating for the route for an email confirmation and verification.
Temporarily closing this issue.
