### ISSUE TITLE
As a developer, I want the the front end build files to be served by the backend

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#54]
When need to serve the entire static folder `./frontend/build` in the main server file on the root route `"/"`.

There is probably a tutorial somewhere.

The result should be navigating to localhost:8080 should show you the react app (as long as the frontend is built. run this command to build the frontend: `cd frontend && npm install && npm run build`)

**Comment by manjari94** [comment]
https://stackoverflow.com/questions/42498555/golang-gin-serving-json-and-static-files-in-the-same-app

**Comment by andrewkucz** [comment]
Closing this, it works now.

Run `sh run.sh` to build the front end and serve the backend.

Running `sh run.sh` and opening localhost:8080 will show the react app now.

Followed this tutorial without issue:  https://medium.com/@synapticsynergy/serving-a-react-app-with-golang-using-gin-c6402ee64a4b
