### ISSUE TITLE
As a developer, I want the Database table to be connected matching the ER model

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#55]
The database and models don't really match how we should be storing the data. The models need the proper associations (and foreign keys and such)

See this GORM page: https://gorm.io/docs/associations.html

This story is to update the backend and database to connect the data in a more conventional DBMS way. Feel free to delete the entire database and start from scratch, I can import the restaurants again if need be

**Comment by carolnavya** [comment]
![WhatsApp Image 2022-03-29 at 5 08 38 AM](https://user-images.githubusercontent.com/36771418/160804130-5dbddd9d-b474-4241-b422-2fde455be563.jpeg)
Updated ER Diagram

**Comment by carolnavya** [comment]
Updated ER model and added foreign constraints between tables
