### ISSUE TITLE
As a developer, I want a basic react app as a foundation

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#7]
Basic skeleton of a react app set up to work off of.

Use `npx create-react-app` to generate a start react project

**Comment by Monicakodali** [comment]
Set up a basic react app to work on further.
References:
[https://www.youtube.com/watch?v=3HMtarQAt3A](url)

**Comment by andrewkucz** [comment]
I'm going to close this since it was covered by the other story.

I used `create-react-app` and built off that in issue #9
